version: '3'
services:
  node:
    restart: always
    build: https://hub.docker.com/repository/docker/mahmoudaboud/nodeapp_test
    ports:
      - 3000:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017
