apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: devops-tools-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs  
    spec:
      containers: 
      - name: nodeapp_test_container
        image: mahmoudaboud/nodeapp_test:latest
        ports:
        - containerPort: 3000
        resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
        env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
        imagePullPolicy: Always
